### ISSUE TITLE
Reflection only supports string based, single keys

### ISSUE THREAD

**Issue by dhubler** [freeconf/yang#18]
When marshalling to/from a collection, in particular when creating items in a collection, keys that are not strings cause a cast exception. when inserting data into collection.

**Comment by dhubler** [comment]
commit af68a4c1add514fda9e6b55fee18fdb5ac89122b (HEAD -> master, origin/master, origin/HEAD)
Author: Douglas Hubler <douglas@hubler.us>
Date:   Wed Jul 20 08:02:51 2022 -0400

    Issue 18 - support for map collection types in relection

**Comment by HRogge** [comment]
I am working with this issue right at the moment and I don't think the current (master) code in nodeutil/reflect.go:307 childMap() is correct
`mapKey := reflect.ValueOf(r.Meta.Ident())`

r.Meta.Ident() returns a string with the (yang) identifier of the container. (golang) `reflect.ValueOf(r.Meta.Ident())` ALWAYS returns a reflection value of type "string" for this (because r.Meta.Ident() returns a string), so something is wrong here.

I ran into this issue because I have a map which use netip.Addr as the key... at the moment I am only trying to get "read access" working (hoping that netip.Addr String() method is enough), but the code panics when calling "MapIndex" in the function mentioned above.
